
"use client"
import { AuthProvider } from '@/context/authContext'
import './globals.css'
import { Inter } from 'next/font/google';
import { QueryClient, QueryClientProvider} from '@tanstack/react-query'

const queryClient = new QueryClient()

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <AuthProvider>

          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>

        </AuthProvider>


      </body>
    </html>
  )
}
